version: '3.3'
services:



  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - 27017:27017
    volumes:
      - "mongodata:/data/db"
    networks:
      - tradewave-network



  prediction-app:
    container_name: prediction_app
    build:
      context: ./prediction_ms
      dockerfile: Dockerfile
    ports:
      - 7651:7651
    depends_on:
      - mongo-db
    networks:
      - tradewave-network
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py crontab add &&
             python stock_prediction_RPA/on_boot.py &
             python manage.py runserver 0.0.0.0:7651"




volumes:
  db-data:
  mongodata:
networks:
  tradewave-network: