version: '3.3'
services:
  user_auth_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./user_auth_ms/init.sql:/data/application/init.sql
    networks:
      - tradewave_network

  user_auth_app:
    container_name: user_auth_app
    build: 
      context: ./user_auth_ms
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - .:/app
    depends_on:
      - user_auth_db
    networks:
      - tradewave_network
      
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - "mongodata:/data/db"
    networks:
      - tradewave_network

  transactions_app:
    container_name: transactions_app
    build:
      context: ./transaction_ms
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mongo_db
    networks:
      - tradewave_network

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq-containter
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - tradewave_network

  graphql:
    container_name: graphql
    restart: always
    build:
      context: ./tradewave_ag
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - tradewave_network
      
volumes:
  db_data:
  mongodata:
networks:
  tradewave_network: